-- Schema Coreautotech ecommerce - Tablas nuevas para compras

-- Compras (modelo de compras online)
create table if not exists public.compras (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete set null,
  cantidad integer not null default 1,
  email_comprador text not null,
  nombre_comprador text not null,
  telefono_comprador text,
  monto_total numeric(12,2) not null,
  estado text not null default 'pago_pendiente', -- pago_pendiente, pago_recibido, aprobado, enviado, entregado, cancelado
  notas text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

-- Comprobantes de pago
create table if not exists public.comprobantes_pago (
  id bigint generated by default as identity primary key,
  compra_id bigint not null references public.compras(id) on delete cascade,
  url_archivo text not null,
  nombre_archivo text,
  estado text not null default 'pendiente', -- pendiente, aprobado, rechazado
  notas_admin text,
  creado_en timestamptz not null default now(),
  revisado_en timestamptz,
  revisado_por text
);

-- Envíos
create table if not exists public.envios (
  id bigint generated by default as identity primary key,
  compra_id bigint not null unique references public.compras(id) on delete cascade,
  empresa_envio text not null, -- andreani, oca, correo_argentino, coordinadora, etc
  numero_tracking text,
  fecha_entrega_estimada date,
  estado text not null default 'pendiente', -- pendiente, listo_para_retirar, enviado, en_transito, entregado, devuelto
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  enviado_en timestamptz
);

-- Notificaciones por email (auditoría)
create table if not exists public.notificaciones_email (
  id bigint generated by default as identity primary key,
  compra_id bigint references public.compras(id) on delete set null,
  email_destinatario text not null,
  tipo_email text not null, -- comprobante_subido, pago_aprobado, listo_para_retirar, envio_tracking
  enviado_en timestamptz not null default now(),
  estado text not null default 'enviado' -- enviado, fallido
);

-- Índices para performance
create index if not exists idx_compras_producto on public.compras(producto_id);
create index if not exists idx_compras_email on public.compras(email_comprador);
create index if not exists idx_compras_estado on public.compras(estado);
create index if not exists idx_comprobantes_compra on public.comprobantes_pago(compra_id);
create index if not exists idx_comprobantes_estado on public.comprobantes_pago(estado);
create index if not exists idx_envios_compra on public.envios(compra_id);
create index if not exists idx_envios_tracking on public.envios(numero_tracking);
create index if not exists idx_notificaciones_compra on public.notificaciones_email(compra_id);

-- Activar Row Level Security
alter table public.compras enable row level security;
alter table public.comprobantes_pago enable row level security;
alter table public.envios enable row level security;
alter table public.notificaciones_email enable row level security;

-- Políticas (permisivas para MVP)
-- Compras: lectura y escritura pública
create policy "compras_lectura" on public.compras for select to public using (true);
create policy "compras_crear" on public.compras for insert to public with check (true);
create policy "compras_actualizar" on public.compras for update to public using (true) with check (true);

-- Comprobantes de pago: lectura y escritura pública
create policy "comprobantes_lectura" on public.comprobantes_pago for select to public using (true);
create policy "comprobantes_crear" on public.comprobantes_pago for insert to public with check (true);
create policy "comprobantes_actualizar" on public.comprobantes_pago for update to public using (true) with check (true);

-- Envíos: lectura y escritura pública
create policy "envios_lectura" on public.envios for select to public using (true);
create policy "envios_crear" on public.envios for insert to public with check (true);
create policy "envios_actualizar" on public.envios for update to public using (true) with check (true);

-- Notificaciones: solo lectura admin (restricto)
create policy "notificaciones_lectura_admin" on public.notificaciones_email for select to public using (false);

-- Triggers para actualizar actualizado_en automáticamente
create or replace function public.actualizar_compras_timestamp()
returns trigger as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$ language plpgsql;

create trigger compras_actualizar_timestamp before update on public.compras
for each row execute procedure public.actualizar_compras_timestamp();

create or replace function public.actualizar_envios_timestamp()
returns trigger as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$ language plpgsql;

create trigger envios_actualizar_timestamp before update on public.envios
for each row execute procedure public.actualizar_envios_timestamp();
