-- Coreautotech ecommerce schema

-- Categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

-- Products
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  in_stock boolean generated always as (stock > 0) stored,
  category_id bigint references public.categories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Product images
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  created_at timestamptz not null default now()
);

-- Orders (manual purchase requests)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete set null,
  quantity integer not null default 1,
  buyer_name text,
  buyer_contact text, -- phone/whatsapp or email
  status text not null default 'nuevo', -- nuevo, en_proceso, cerrado, cancelado
  notes text,
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_products_category on public.products(category_id);
create index if not exists idx_product_images_product on public.product_images(product_id);
create index if not exists idx_orders_product on public.orders(product_id);

-- Enable Row Level Security
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.orders enable row level security;

-- Policies (initially permissive for MVP; tighten later)
-- Read policies
create policy "categories_read" on public.categories for select to public using (true);
create policy "products_read" on public.products for select to public using (true);
create policy "product_images_read" on public.product_images for select to public using (true);
create policy "orders_read_admin_only" on public.orders for select to public using (false);

-- Write policies
-- Allow creating orders from the public site (no auth), MVP only
create policy "orders_insert_public" on public.orders for insert to public with check (true);

-- Allow product and category writes (MVP only). Replace with proper admin auth later.
create policy "categories_write_mvp" on public.categories for all to public using (true) with check (true);
create policy "products_write_mvp" on public.products for all to public using (true) with check (true);
create policy "product_images_write_mvp" on public.product_images for all to public using (true) with check (true);

-- Trigger to update updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger products_set_updated_at before update on public.products
for each row execute procedure public.set_updated_at();

-- Seed
insert into public.categories (name, slug) values
  ('Repuestos', 'repuestos') on conflict do nothing,
  ('Pantallas CarPlay', 'pantallas-carplay') on conflict do nothing,
  ('Faroles Tuning', 'faroles-tuning') on conflict do nothing,
  ('Volantes Tuning', 'volantes-tuning') on conflict do nothing;
